#!/usr/bin/env bash
set -euo pipefail

echo "Building..."

spago build

pslua --foreign-path . --ps-output output --entry Lua.Ngx --lua-output-file dist/Lua.Ngx.lua
pslua --foreign-path . --ps-output output --entry Lua.Ngx.Http.Status --lua-output-file dist/Lua.Ngx.Http.Status.lua
